#!/usr/bin/env python
from __future__ import division

import pyaudio
import wave
import sys

from numpy import *
from numpy.fft import fft


def get_volume(seconds=1):
    chunk = 1024
    format = pyaudio.paInt16
    channels = 1
    sample_rate = 44100

    p = pyaudio.PyAudio()

    stream = p.open(format = format,
                    channels = channels,
                    rate = sample_rate,
                    input = True,
                    frames_per_buffer = chunk)

    all = ''
    for i in range(0, int(sample_rate / chunk * seconds)):
        data = stream.read(chunk)
        all += data

    stream.close()
    p.terminate() 

    audio_data = fromstring(all, dtype=short)
    normalized_data = audio_data / 32768.0
    fft_data = fft(normalized_data)[1:1 + chunk / 2]
    fft_data = abs(fft_data)
    return sum([float(a) for a in fft_data]) / len(fft_data)


def main():
    while 1:
        v = get_volume(seconds=20)
        print(v)

if __name__ == '__main__':
    main()

